name: Maven & Docker & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
        build:
                name: Compile, Build Native, Build Docker Image, Push on Github
                runs-on: ubuntu-latest

                steps:
                        - name: Git Checkout
                          uses: actions/checkout@v3
                          with:
                                  fetch-depth: 1
                        - name: Java 17 Setup
                          uses: actions/setup-java@v2
                          with:
                                  distribution: 'adopt' # See 'Supported distributions' for available options
                                  java-version: '17'

                        - name: Bump Version and Push Tag
                          id: tag_version
                          uses: mathieudutour/github-tag-action@v6.0
                          with:
                                  github_token: ${{ secrets.GITHUB_TOKEN }}
                                  default_bump: patch
                                  tag_prefix: ""

                        - name: Cache local Maven repository
                          uses: actions/cache@v2
                          with:
                                  path: ~/.m2/repository
                                  key: ness_java
                                          
                        - name: Maven Package
                          run: mvn clean package -DskipTests=true
                          
                        - name: Publish Image
                          uses: matootie/github-docker@v3.1.0
                          with:
                                containerRegistry: true
                                accessToken: ${{ github.token }}
                                contextName: src/main/docker/Dockerfile.jvm
                                tag: |
                                  latest
                                   ${{ steps.tag_version.outputs.new_tag }}
                        
                        
